default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    - id: isort
      entry: isort
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      entry: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
